run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - prealloc
    - bodyclose
    - nilerr

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: false
      - name: var-naming
        disabled: false
  goimports:
    local-prefixes: github.com/ckumar392/zonegit

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
